Project popup
KanzaTahreem/Portfolio-Website pull request #12
Opened 2022-09-06 22:43 UTC by KanzaTahreem

This pull request covers the following requirements

### Project requirements

- You should implement the following interactions:
  - When the user clicks (or taps) the button to check project details, the popup with details about the project appears.
  - When the user clicks (or taps) the close (X) button, the popup disappears.

- In order to associate each project with the popup window details, you must refactor the project section:
  - You need to use **a JavaScript array to store all of the information for all projects**.
  - For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, and link to the source.
  - You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
  - After that, you could implement the popup window.
- You should implement popups for both mobile and desktop screen sizes.

2022-09-06 23:15 UTC, tufoinnkuo10 requested changes
Hi @KanzaTahreem 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ popup goten dynamically from script array
✅ design well followed

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-09-06 23:15 UTC, tufoinnkuo10 commented on script.js
> +      techStack: 'Back End Dev',
- [ ] great job so far. please ensure that the mobile version of popup is full heigth like that of figma

yours
![Screenshot (429)_LI](https://user-images.githubusercontent.com/65298048/188755005-864d643d-6ad8-4bff-a4d4-1b5da77f6451.jpg)
figma
![Screenshot (430)](https://user-images.githubusercontent.com/65298048/188755024-ce2328d8-4aa5-4918-9fe6-050e8702cee1.png)

2022-09-06 23:15 UTC, tufoinnkuo10 commented on script.js
> +      highlight: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
- [ ] please kindly add the popup image size for the desktop version so it looks like that of figma
- [ ] increase the close icon a little and bring it inside to make it more visible
- [ ] Kindly add your description font size(16px) like that of figma

yours
![Screenshot (435)_LI](https://user-images.githubusercontent.com/65298048/188755742-2ad9db31-a527-4762-abf2-87a9ba2e811d.jpg)
figma
![Screenshot (431)](https://user-images.githubusercontent.com/65298048/188755836-e5217d7e-53b8-44e4-8d04-30b5754e73fa.png)

2022-09-06 23:15 UTC, tufoinnkuo10 commented on script.js
> +      src: './images/second-section/project-02.svg',
- [ ] please kindly make the mobile version responsive when switching to deskstop version
![Screenshot (435)](https://user-images.githubusercontent.com/65298048/188756107-2c3ae21c-fe14-4052-81b8-26c40a9e2012.png)

2022-09-07 16:33 UTC, dasileker approved these changes
### **Hi @KanzaTahreem,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 
### **Note**

- `Please make sure that your readme file is having the right Author name right you have multiple Authors.`


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-07 16:55 UTC, merged